### ISSUE TITLE
shared memory allocation issue

### ISSUE THREAD

**Issue by psychocoderHPC** [alpaka-group/alpaka#1257]
Allocating shared memory with CPU accelerators within a function which is called from a loop will result into allocation issues due to the limited shared memory per block (64kib)

```
Assertion `m_allocdBytes <= m_capacity' failed.
```

pseudo example:
```
foo()
{
  auto& sharedMem
    = alpaka::declareSharedVar<char * [1024], __COUNTER__>(acc);
}

main()
{
  for(int i = 0; i < 1000; ++i)
    foo();
}
```

For CUDA this is not a problem because calling `declareSharedVar` with the same id, here provided by `__COUNTER__` will reverence always to the same memory and only allocated shared memory once.
This strange CUDA behavior was in the past the reason why we introduced the unique id for `declareSharedVar`.
Reusing shared memory could be intended by the user e.g. in mallocMC https://github.com/alpaka-group/mallocMC/blob/00df9a5b7c33ae7ca70fcab9cc77951c098dfb6b/src/include/mallocMC/distributionPolicies/XMallocSIMD.hpp#L126

We do not declare in alpaka how `declareSharedVar` should be used or what is forbidden. Based on the definition we can fix this issue.

**Comment by psychocoderHPC** [comment]
I am currently working on a fix that should provide the same workflow we have on GPU's. 
I try to fix it so that shared memory allocation on CPU accelerator behave like in CUDA to avoid that we break already ported CUDA code.

**Comment by jkelling** [comment]
Is there an Alpaka best practices guide, where we could advise to avoid doing this? Because larger kernels with many shared variables doing what your example does will suffer severe performance loss with all backends but CUDA and HIP.

Btw: I understand, that this issue exists to be as compatible as possible with CUDA to make cupla work. On the other hand, CUDA allows declaring `__shared__` at global scope, which cannot work in Alpaka/cupla and thus already breaks the illusion CUDA equivalence. Maybe it would not be too bad to, in the interest of performance, go one step further and deviate in this respect too. This would be a breaking change, but worth considering before a major release, IMHO.

**Comment by psychocoderHPC** [comment]
> Is there an Alpaka best practices guide, where we could advise to avoid doing this? Because larger kernels with many shared variables doing what your example does will suffer severe performance loss with all backends but CUDA and HIP.
> 
> Btw: I understand, that this issue exists to be as compatible as possible with CUDA to make cupla work. On the other hand, CUDA allows declaring `__shared__` at global scope, which cannot work in Alpaka/cupla and thus already breaks the illusion CUDA equivalence. Maybe it would not be too bad to, in the interest of performance, go one step further and deviate in this respect too. This would be a breaking change, but worth considering before a major release, IMHO.

Best practices can be added to the docs.
I am for changing current concepts only if there is a better programming model coming into alpaka. For now I do not see any benefits if we restrict the usage.
In most cases you will not pass more then a hand full variables into the shared memory. Aliasing is with this PR not very expensive.
