### ISSUE TITLE
CI: Ubuntu 16.04 is deprecated

### ISSUE THREAD

**Issue by j-stephan** [alpaka-group/alpaka#1348]
Ubuntu 16.04 images will be removed from GitHub Actions in September: https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/

Time to upgrade our CI runners which still use 16.04.

**Comment by BenjaminW3** [comment]
We are somehow safe with respect to the change mentioned above because we only use `ubuntu-18.04`, `ubuntu-20.04` and `ubuntu-latest` as runners.
 However we do not execute the CI (install/compile/run tests) directly within this environment, but we load clean ubuntu docker images first and run inside those. There we are still using `ubuntu:16.04`. Even though it was an LTS release, the 5 years of support already ended in April.
 I will try to replace them by `ubuntu:18.04`.
