### ISSUE TITLE
add threadFence<>

### ISSUE THREAD

**Issue by BenjaminW3** [alpaka-group/alpaka#14]
- [ ] __threadfence_block()
Waits until all GM and SM accesses made by the calling thread prior to __threadfence_block() are visible to all threads in the thread block.
- [ ] __threadfence()
Waits until all GM and SM accesses made by the calling thread prior to the call are visible to:
• threads in the thread block for shared memory accesses and
• threads in the device for global memory accesses.
Prevents the compiler from optimizing by caching shared memory writes in registers.
It does not synchronize the threads and it is not necessary for all threads to actually reach this instruction.
  gcc: __sync_synchronize();
  intel: _mm_mfence();
  MSVC: MemoryBarrier();
  OpenMP: #pragma omp flush
- [ ] __threadfence_system()
waits until all GM and SM accesses made by the calling thread prior to __threadfence_system() are visible to:
• threads in the thread block for shared memory accesses,
• all threads in the device for global memory accesses,
• host threads for page-locked host memory accesses.

**Comment by j-stephan** [comment]
We would like to get this into alpaka 0.7.0. However, this requires #38 to be resolved.

**Comment by bernhardmgruber** [comment]
@j-stephan does it depend on #38? I think this is a separate piece of functionality.

**Comment by j-stephan** [comment]
I thought we agreed that there is a dependency. At least that is how I wrote it down in my notes....

Shouldn't this tie into the envisioned accessor/cursor functionality?

**Comment by j-stephan** [comment]
We have received a user request for thread fences: https://github.com/cms-patatrack/pixeltrack-standalone/pull/181

This is now a high-priority item for the 0.8 release.

**Comment by fwyzard** [comment]
Regarding `__threadfence()`, are you sure about

> Prevents the compiler from optimizing by caching shared memory writes in registers.

?

The current CUDA documentation on [Memory Fence Functions](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#memory-fence-functions) says
> Note that for this ordering guarantee to be true, the observing threads must truly observe the memory and not cached versions of it; this is ensured by using the `volatile` keyword as detailed in Volatile Qualifier.

**Comment by fwyzard** [comment]
For the parallel CPU backends, do you think that `std::atomic_thread_fence(std::memory_order_acq_rel)` gives the same guarantees as `__threadfence()` ?

**Comment by j-stephan** [comment]
Sorry for responding so late, I only now had the time to look into this. The following partly serves as an answer to you but also as my notes before I (or another alpaka developer) start(s) implementing this. Feel free to correct me on anything I might have understood wrong.

## Differences between CPU and GPU fences

### Memory ordering

> For the parallel CPU backends, do you think that `std::atomic_thread_fence(std::memory_order_acq_rel)` gives the same guarantees as `__threadfence()`?

It gives *at least* the same guarantees as `__threadfence()`. Assuming I understand the CUDA documentation correctly, `__threadfence()` and its siblings guarantee the following (regardless of the memory type we are accessing):

1. * This thread: `Load` operations occurring before the fence will always happen before `Load` operations after the fence (`LoadLoad`).
   * Other threads: No effect.
2. * This thread: `Store` operations occurring before the fence will always happen before `Store` operations after the fence (`StoreStore`).
   * Other threads: **At some unknown point in time** this thread's `Store` pre-fence operations become visible to the other threads. Consequently, the other threads' `Load` operations may happen **before or after** this thread's `Store` operations are visible to them.

Now we bring in `std::atomic_thread_fence(std::memory_order_acq_rel)` which introduces a third guarantee in addition to the above:

3. * Same thread: `Load` operations occurring before the fence will happen before `Store` operations after the fence (`LoadStore`).
   * Other threads: No effect.

Note that both approaches are missing `StoreLoad`. This is where CUDA's `__syncthreads` is required which also has other implications (like waiting) and is thus more expensive.

### Cache coherency issues

On CPUs we have cache coherency protocols so we don't need to guard our memory in a special way. On CUDA devices this is different:

> Note that for this ordering guarantee to be true, the observing threads must truly observe the memory and not cached versions of it; this is ensured by using the `volatile` keyword as detailed in [Volatile Qualifier](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#volatile-qualifier).

The corresponding section reads:

> The compiler is free to optimize reads and writes to global or shared memory (for example, by caching global reads into registers or L1 cache) as long as it respects the memory ordering semantics of memory fence functions and memory visibility semantics of synchronization functions.
> 
> These optimizations can be disabled using the volatile keyword: If a variable located in global or shared memory is declared as volatile, the compiler assumes that its value can be changed or used at any time by another thread and therefore any reference to this variable compiles to an actual memory read or write instruction.

This means that we need to use CUDA's `volatile` for memory we want to share with other threads. Since this different from standard C++'s `volatile` we don't want to put `volatile` directly in the kernel, though.

### System fences

CUDA provides the `__threadfence_system()` call which indeed affects the whole system:

> `void __threadfence_system();`
> 
> acts as `__threadfence_block()` for all threads in the block of the calling thread and also ensures that all writes to all memory made by the calling thread before the call to `__threadfence_system()` are observed by all threads in the device, host threads, and all threads in peer devices as occurring before all writes to all memory made by the calling thread after the call to `__threadfence_system()`. 

I think we should not provide an alpaka equivalent to this because it would be too hard / impossible to implement for non-CUDA/HIP back-ends.

## Implications for alpaka (tl;dr)

- [ ] We should implement fences based on CUDA's `__threadfence()` because of its weaker guarantees. This means that we need to document that alpaka guarantees `LoadLoad` and `StoreStore` but **not** `LoadStore`.
- [ ] We need to introduce a new macro / alpaka keyword for usage inside the kernel which abstracts away CUDA's `volatile`.
- [ ] We should not provide an equivalent for `__threadfence_system()` because it is too hard to implement for non-CUDA/HIP backends.

**Comment by fwyzard** [comment]
Thanks for the write up !

After reading it, and re-reading the CUDA and the C++ documentation, I'm wondering how easy/hard/doable it really is to write an abstraction the expands to `__threadfence` + `volatile` for the CUDA backend and `std::atomic_thread_fence` + atomics for standard C++ ...

Maybe it would be easier to build on top of libcu++'s atomic support instead ?

**Comment by j-stephan** [comment]
> After reading it, and re-reading the CUDA and the C++ documentation, I'm wondering how easy/hard/doable it really is to write an abstraction the expands to `__threadfence` + `volatile` for the CUDA backend and `std::atomic_thread_fence` + atomics for standard C++ ...

I'm currently looking into designing something like this:

```c++
template <typename TAcc>
ALPAKA_FN_ACC auto operator()(TAcc const& acc, ALPAKA_NO_MEM_OPT float* ptr, /* ... */)
{
    auto x = ptr[/* ... */];
    alpaka::mem_fence(acc, alpaka::memory_scope::device);
    auto y = ptr[/* ... */];
}
```

`ALPAKA_NO_MEM_OPT` would be a macro that turns into `volatile` on CUDA/HIP platforms and into nothing everywhere else. I'm also open to name suggestions. What do you think?

> Maybe it would be easier to build on top of libcu++'s atomic support instead ?

libcu++ was only recently introduced (CUDA 11.2 IIRC) and we still have to support older CUDA versions. Apart from that, I'm also not sure how this would interact with HIP. But in principle this is a direction we should explore in the future.

**Comment by fwyzard** [comment]
> libcu++ was only recently introduced (CUDA 11.2 IIRC) and we still have to support older CUDA versions.

I think one can use the current version of libcu++ with older CUDA versions, if the required features are available.
But I see your point about older releases.

> Apart from that, I'm also not sure how this would interact with HIP. But in principle this is a direction we should explore in the future.

Good point, I hadn't thought about it.

**Comment by fwyzard** [comment]
> `ALPAKA_NO_MEM_OPT` would be a macro that turns into `volatile` on CUDA/HIP platforms and into nothing everywhere else. I'm also open to name suggestions. What do you think?

`ALPAKA_VOLATILE` or `ALPAKA_DEVICE_VOLATILE` ?

**Comment by j-stephan** [comment]
I like `ALPAKA_DEVICE_VOLATILE`!
