### ISSUE TITLE
ALPAKA_CXX_VERSION cmake variable is overwritten if alpaka is included in a project

### ISSUE THREAD

**Issue by SimeonEhrig** [alpaka-group/alpaka#1415]
The following example is not working:

```cmake
set(ALPAKA_CXX_STANDARD "17")

# ALPAKA_CXX_STANDARD is 17
find_package(alpaka)
# ALPAKA_CXX_STANDARD is 14
```
The reason is the following line of code:
https://github.com/alpaka-group/alpaka/blob/261bdf70f359b3d97dfdfb3cc2bd39ec0472c8d1/cmake/alpakaCommon.cmake#L128

A cached variable always overwrites a normal (non-cached) variable. Therefore we have to two options. 

1. The project, who is using alpaka, needs to declare the `ALPAKA_CXX_STANDARD` variable as cached:

```cmake
set(ALPAKA_CXX_STANDARD "17" CACHE STRING "C++ standard version") 

# ALPAKA_CXX_STANDARD is 17
find_package(alpaka)
# ALPAKA_CXX_STANDARD is 17
```
2. We cover the case in the cmake file, if the `ALPAKA_CXX_STANDARD` is already set and does not overwrite it.

I'm strongly for option two. What do you think?

The problems does not affected cached variables, which are defined by the function `option`. They don't overwrite cached variables. This behavior is also adapted for cached variables, defined via `set` in CMake 3.21: https://cmake.org/cmake/help/latest/release/3.21.html#other-changes

**Comment by psychocoderHPC** [comment]
IMO from my limited cmake knowledge, I would also say option two sounds reasonable.

**Comment by j-stephan** [comment]
I agree, option 2 sounds good.

**Comment by SimeonEhrig** [comment]
Okay, I prepare a fix. I think, it feels more common to use simply `set(ALPAKA_CXX_STANDARD 17)` and I think this is also the reason why the CMake developer changes the default behavior of cached variables.

**Comment by BenjaminW3** [comment]
I would also vote for option 2

**Comment by bernhardmgruber** [comment]
How about option 3, dropping `ALPAKA_CXX_STANDARD`?

**Comment by j-stephan** [comment]
I vaguely remember this not being an option because of some evil hackery in other places. @psychocoderHPC, do you have any insight?

**Comment by SimeonEhrig** [comment]
I think, we should discuss `ALPAKA_CXX_STANDARD` in the meeting next week.  I found also some interesting "side effects" beside the behavior of `set(ALPAKA_CXX_STANDARD xx)`.

- The standard is only correct set, if you link your target with the `alpaka::alpaka` target. It will not set, if you use `alpaka_add_executable` or `alpaka_add_library`.
- The `CXX_STANDARD` and maybe the `CUDA_CXX_STANDARD` are not affected by the `ALPAKA_CXX_STANDARD`. This can be a problem for example, if you use `add_executable` and `add_library` to compile a file with the g++ instead the nvcc.

I already wrote a test, to verify how to use the `ALPAKA_CXX_STANDARD` correctly with `vikunja`: https://github.com/alpaka-group/vikunja/pull/38

**Comment by psychocoderHPC** [comment]
> How about option 3, dropping `ALPAKA_CXX_STANDARD`?

As I know we can not drop the variable else we can not set CXX standard for CUDA or HIP

CUDA:
`target_compile_features(alpaka INTERFACE cuda_std_${ALPAKA_CXX_STANDARD})`

HIP
`alpaka_set_compiler_options(HOST_DEVICE target alpaka -std=c++${ALPAKA_CXX_STANDARD})`

**Comment by bernhardmgruber** [comment]
Ideally, I would like the `cuda_std_...` to be the same as the `cxx_std_...` but for the target that links against alpaka. I am trying to play with generator expressions, but it seems I cannot get it working yet. Something like:
```
        target_compile_features(alpaka INTERFACE 
            $<$<COMPILE_FEATURES:cxx_std_14>:cuda_std_14>
            $<$<COMPILE_FEATURES:cxx_std_17>:cuda_std_17>
            $<$<COMPILE_FEATURES:cxx_std_20>:cuda_std_20>
        )
```
So the CUDA standard would be always the same as the actual CXX standard of the final target (not the `alpaka` target).

The reason why I would like that is this:

```
find_package(alpaka) # ALPAKA_CXX_STANDARD == 14 per default, cxx_std_14 and cuda_std_14 (if CUDA backend enabled)
find_package(llama) # llama target has cxx_std_17
add_executable(myprogram ...)
target_link_libraries(myprogram PUBLIC alpaka::alpaka llama::llama)
# target_compile_features(myprogram PUBLIC cxx_std_20)
```
So if I use a CPU backend, `myprogram` compiles with `-std=c++17` (as required by llama) and all is fine. If I request `cxx_std_20` myself, then `myprogram` is compiled with `-std=c++20`, also good. In both cases, `ALPAKA_CXX_STANDARD` is superseded by higher `cxx_std...`
However, if I use the CUDA backend, the `cxx_std_17` of the `llama` target or the manually requested `cxx_std_20` is ignored, because alpaka sets the compiled language to CUDA (which is fine), but then `ALPAKA_CXX_STANDARD` kicks in and I get C++14, which leads to compile failures with `llama`. However, I can also not set `cuda_std_17` for `llama`, because now CMake requires a CUDA compiler, even if I disable the CUDA backend. And CMake generator expressions are not allowed for compile features to conditionally enable `cuda_std_17` in llama.

Note that this is not a llama specific problem, but actually an issue on how the CXX and CUDA standard of alpaka interplays with other libraries.

**Comment by SimeonEhrig** [comment]
@j-stephan Should this lands also in alpaka 0.8?

**Comment by j-stephan** [comment]
Ah, it wasn't assigned to the project so I haven't seen this yet. Do you have the time to provide a PR this week?

**Comment by SimeonEhrig** [comment]
I think I can do it now. Should be not much work.

**Comment by SimeonEhrig** [comment]
solved
