### ISSUE TITLE
add iDevice() to DevUniformCudaHipRt and DevCpu

### ISSUE THREAD

**Issue by fwyzard** [alpaka-group/alpaka#1427]
Would it be possible to add an `iDevice()` method to `DevUniformCudaHipRt` and `DevCpu` ?

Currently
  - `DevOacc` and `DevOmp5` have a private `m_iDevice` member, and a public `iDevice()` method
  - `DevUniformCudaHipRt` has a public `m_iDevice` member
  - `DevCpu` has neither (can be assumed to be always `0`)

For writing generic code, it would be nice if all devices exposed the same interface (directly or via traits / accessors).

**Comment by j-stephan** [comment]
This seems reasonable. I think the OpenACC / OpenMP 5 back-ends are in error here. alpaka should not hide / encapsule underlying back-end specifics, only provide a means to interact with them in an abstract way.

I'm not sure about `DevCpu` always being `0`, though. How would this interact with multi-CPU machines?

**Comment by fwyzard** [comment]
As far as I could see, Alpaka assumes that there is a single CPU device, which has (for example when using the TBB backend) as many cores as the total number of cores in the system.

Changing that to separate CPU devices (e.g. for machines with multiple sockets or multiple NUMA nodes per socket) could be interesting - but likely to require some general rethinking, especially for the "host" device.

**Comment by jkelling** [comment]
@j-stephan note, that `m_iDevice` is a member of [`detail::DevOaccImpl`](https://github.com/alpaka-group/alpaka/blob/develop/include/alpaka/dev/DevOacc.hpp#L46), not `DevOacc`. Both provide the getter.

* The getter in `DevOacc` is necessary because it is very wierd, if outside code using an implicitly-shared object like `DevOacc` has to access the (kinda)PIMPL directly.
* One can argue about the getter in `detail::DevOaccImpl`: The members could be public, as the instance is private within `DevOacc`. I prefer to make as many things as possible private because it prohibits unintented interdependencies (spagetti code) which could lead to bugs in later refactorings.

The same applies to `DevOmp5`.

There are many places in the the alpaka code base were implcitly-shared objects are sloppily implemented. I tried to avoid this in these new backends.

**Comment by fwyzard** [comment]
From a user perspective, it makes sense that `m_iDevice` is private: I would assume that I should not change it by hand from outside the object to (try and) change the active device.

**Comment by jkelling** [comment]
@fwyzard What exactly are your using the device id for in your code? The backend's `Dev..` is the only handle for a device that should be used by user-code. Any property relevant to the user should have a trait. There is no `getDeviceId` trait because the device id is an implementation detail (in theory, backends could exist in which there are multiple devices, but no numerical device id, only some other handle type, to identify them).

**Comment by fwyzard** [comment]
One use case is to have a collection of objects, one per device: a progressive numerical index allows for a faster and more compact representation (_e.g._ an `std::vector<T>`) than a generic handle (_e.g._ an `std::map<Device, T>`).

So, we don't need the device index to correspond to the underlying identifier used by the backend (for example, that could be the full PCI ID of the device), but we would like to have a progressive numerical index.

Of course we could build the mapping in the client code, for example at the job startup - but if Alpaka is already using an index, we are happy to reuse it :-)

**Comment by jkelling** [comment]
Indexing `std::vector` with a device ID is not save in OpenMP target: Note, that `m_iDevice` is of type `signed int`, this is not any accident. You can target the host device, the device id of which is returned by [`omp_get_initial_device()`](https://www.openmp.org/spec-html/5.0/openmpsu150.html#x187-8820003.2.41). The returned value is implementation-defined. Many implementations chose `-1` (But I have also seen `-4` or something).

*Edit (in case someone reads this in the future):*
The initial device can be selected like [`getDevByIdx<PltfOmp5>(getDevCount<PltfOmp5>())`](https://github.com/alpaka-group/alpaka/blob/develop/include/alpaka/pltf/PltfOmp5.hpp#L62).

**Comment by fwyzard** [comment]
Mhm, thanks for the info.

We don't need this id for the host device, only for the accelerator devices, but I take your point.

**Comment by j-stephan** [comment]
Shifting to 0.9.
