### ISSUE TITLE
Use `if constexpr`

### ISSUE THREAD

**Issue by j-stephan** [alpaka-group/alpaka#1500]
Since we heavily rely on template metaprogramming we should investigate where we can (sensibly) use `if constexpr` instead of `std::enable_if` and friends.

**Comment by psychocoderHPC** [comment]
Note: For such a refactoring keep the design principles of alpaka in mind. `std::enable_if` is mostly used together with SFINAE to keep alpaka extendable from the user/thrid-party code outside of alpaka. 
Never the less I thing we have some places where `if constexpr` would make the implementation much easier because such parts are not extendable or exposed to the user of alpaka.
