### ISSUE TITLE
Ci: openAcc test show illegal memory access

### ISSUE THREAD

**Issue by psychocoderHPC** [alpaka-group/alpaka#1550]
As mentioned https://github.com/alpaka-group/alpaka/pull/1549#issuecomment-998748452 the openAcc runtime test is showing illegal memory access, the reason is not clear:

[linux_nvhpc-21.9_cuda-11.4_oacc](https://gitlab.com/hzdr/crp/alpaka/-/jobs/1907538789) fails on gitlab CI with call to cuStreamSynchronize returned error 700: Illegal address during kernel execution. I suppose this is still the same error as in the original report
```
      Start  9: randomCells2D
9: Test command: /builds/hzdr/crp/alpaka/build/example/randomCells2D/randomCells2D
9: Test timeout computed to be: 1500
9: Failing in Thread:1
9: call to cuStreamSynchronize returned error 700: Illegal address during kernel execution
9: 
 9/37 Test  #9: randomCells2D ....................***Failed    1.14 sec
test 10
```

CC-ing: @jkelling could you have a look into the issue next year, please.

**Comment by jkelling** [comment]
I had no success reproducing this issue locally (Kepler GPU) using the branch from #1549 (passes for me). Will have to try a different machine with a Pascal GPU.

**Comment by jkelling** [comment]
No luck on P100 and V100 either: passes on both.

The flags are identical to the ones use in CI (This is important as passing optimization flags or `-g` to nvc++ will make things go wrong):
```
-DALPAKA_ACC_ANY_BT_OACC_ENABLED -DALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLED -DALPAKA_BLOCK_SHARED_DYN_MEMBER_ALLOC_KIB=47 -DALPAKA_DEBUG=0 -DALPAKA_OFFLOAD_MAX_BLOCK_SIZE=256 -DBOOST_ALL_NO_LIB -D__GCC_ATOMIC_TEST_AND_SET_TRUEVAL=1 -I<alpaka/include> -I<boost/1.74.0/include> -acc -ta=tesla "--diag_suppress 177" -acc --c++17 --gnu_extensions
```

**Comment by jkelling** [comment]
It also passes if run on the CI node, but outside of a container. I.e. there may be some issue with the container.

@psychocoderHPC do you have any idea if compiler flags might be passed in the CI environment by a mechanism which makes them not show up on the command line printed by cmake, via `$CXXFLAGS`.

**Comment by jkelling** [comment]
Ok I found the issue.

The CI OpenACC backend was hardcoded to only have two threads per block in the CI, which was the difference local runs and CI.

The issue is related to how NVHPC's runtime handles block/gang-local variables by placing it in global device memory, not actually in (CUDA) shared memory. It seems like it allocates memory for each block in a kernel, this way kernels with many blocks may run out of memory. There are two possible fixes:
1. Reduce `ALPAKA_BLOCK_SHARED_DYN_MEMBER`
2. Increase the number of threads per block to reduce the number of blocks. I will fix the code to actually respect `ALPAKA_OFFLOAD_MAX_BLOCK_SIZE` in CI and thus run 256 threads.
