### ISSUE TITLE
Accessors for 0-sized buffers and views

### ISSUE THREAD

**Issue by fwyzard** [alpaka-group/alpaka#1558]
As a follow up to #1536 and #1433, I would like to add a specialisation for accessors for 0-dimensional (scalar) buffers and views.

Since for a scalar the `[]` operator does not make much sense, what interface do you prefer ?
  - add an `operator T&()` or `operator T const&() const` conversion operator to the underlying scalar type[^1]
  - add the `*` and `->` operators  
  - something else

[^1]: I'm not sure if this could support write-only access, though

**Comment by fwyzard** [comment]
@bernhardmgruber what do you think ?

**Comment by j-stephan** [comment]
Note that @bernhardmgruber is still on vacation (until next week I believe). It might take a while before he answers to this.

**Comment by bussmann** [comment]
I would think option 1 looks most natural...

**Comment by bernhardmgruber** [comment]
I remember @fwyzard proposing `operator*` and `operator->` for 0-dim buffers, so using the same syntax for accessor seems the most appropriate.

Write-only access is generally problematic, since we have to use proxy references to restrict reading a memory reference. Also because the C++ language does not offer a propagating language support like `const` to model this. So I have no way to give you for example a write-only memory reference to a class type, through which you can access members. You would always have to create an instance as a local variable, access members there and then only write through the reference.
I have no better solution for write-only accessors yet.

**Comment by fwyzard** [comment]
> I remember @fwyzard proposing `operator*` and `operator->` for 0-dim buffers, so using the same syntax for accessor seems the most appropriate.

Indeed... In fact, I'm asking because I'd like to implement a consistent interface for 0-sized buffers and accessors: either both of them have  `operator*` and `operator->`, or both have `operator T&()` _etc._

I don't have a strong preference either way, hence my question :-)

> Write-only access is generally problematic [...]

Agreed.

So far it's not something we are interested in, but I would try to add it for consistency.

**Comment by fwyzard** [comment]
After thinking it through, this

> I remember @fwyzard proposing `operator*` and `operator->` for 0-dim buffers, so using the same syntax for accessor seems the most appropriate.

seems like the best approach.

The reason is that 0-dim buffers are often going to be complex structures, for which it is important to have a simple way of accessing data members or methods. This is simple with the `->` operator, but much more complex with a `T&` cast operator.

This approach also matches interface of the usual smart pointeres (`srd::unique_ptr` and `std::shared_ptr`), with the `*` and `->` operators for scalars and the `[]` operator for arrays.
