### ISSUE TITLE
Which CPU atomic implementation should be enabled by default?

### ISSUE THREAD

**Issue by j-stephan** [alpaka-group/alpaka#1572]
As a follow up to #1566:

We need to decide which CPU atomics implementation should be enabled by default.

### `boost::atomic_ref`

+ Pro: better performance
+ Con: hard **runtime** dependency on Boost.Atomic

### lock-based

+ Pro: no runtime dependency, alpaka is still header-only
+ Con: worse performance

@alpaka-group/alpaka-maintainers Please discuss (once you are back...)

**Comment by bernhardmgruber** [comment]
I prefer `boost::atomic_ref` because it's faster. We already have runtime dependencies like Boost.Fiber, CUDA, HIP, TBB, OpenMP, pthread, etc. It's true that this is the first time we have a runtime dependency for the most simple serial backend. But I would argue that the backends for production use always need third-party runtime dependencies. Furthermore, you can also link boost statically and avoid the *runtime* dependency. Also C++20 will include `std::atomic_ref` as a replacement for `boost::atomic_ref`.

**Comment by ax3l** [comment]
> Also C++20 will include std::atomic_ref as a replacement for boost::atomic_ref.

Not sure if that's done already, but when Alpaka is built in C++20 even today, you could already do that switch automatically.

Since we still depend on Boost for at least predef #481, just depend on it for now. We could aim to get boost as a fully optional dependency with a C++20 switch, for instance.

If we get all other non-optional dependencies out before that switch, I would make this optional. You can still warn about performance in configs & configure for that backend if no boost is found and the compiler does not yet support [C++20](https://en.cppreference.com/w/cpp/compiler_support#C.2B.2B20_library_features).

**Comment by j-stephan** [comment]
CC @psychocoderHPC and @SimeonEhrig

**Comment by SimeonEhrig** [comment]
Is there any problem, to check what is available on compile time? If not, I would order it by performance and use the most fasted, available version.

**Comment by psychocoderHPC** [comment]
IMO using boost `atomic_ref` if available is fine but if not we should fall back to the original compile-time hash table implementation.
Never the less we should add an CMake option which is by default set to `AUTO` where we can force disable that `boost::atomic_ref` is used or force enable it.
