### ISSUE TITLE
[RFC] Drop support for clang-5

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#1747]
Clang-5 was released on 2017-09-07, and its sucessor, clang-6, was released on 2018-03-08, over 4 years ago. I propose to drop support for clang-5 to reduce maintenance effort on our side.

This is also motivated by a CI failure where clang-5 is unable to perform CTAD in presence of a deduction guide: https://github.com/alpaka-group/alpaka/runs/6982333374?check_suite_focus=true#step:5:5164

**Comment by j-stephan** [comment]
I'm okay with this. IIRC @psychocoderHPC was proposing to keep clang 5 and 6 during the last compiler purge (because so far they supported all features we require) so I suggest we wait for his opinion.

If this goes through please also remove all clang-5/6 work-arounds that are present in our code base.

**Comment by SimeonEhrig** [comment]
I'm also for removing it. I think dropping a Clang version is not so complicated because of 3 reasons.

1. You can use GCC and clang for the same result and GCC has the bigger user base (for example, CUDA has no real alternative).
2. Most of the time, you need to install clang by yourself and therefore you have also the knowledge to install another version.
3. Clang 5 is not available in the official llvm apt repository on Ubuntu 20.04: https://gitlab.hzdr.de/ehrig49/alpaka-group-container/-/blob/master/generator/generator.py#L518

**Comment by psychocoderHPC** [comment]
If it is blocking because there is a bug or it is not fully supporting the standard we support then drop clang5.
Since you mentioned CTAD is not supported I am for removing clang5.

**Comment by j-stephan** [comment]
I can kill clang-5 as part of #1713 since I need to do more work there anyway. Does the CTAD issue also appear with clang-6?

**Comment by bernhardmgruber** [comment]
> Does the CTAD issue also appear with clang-6?

No, clang-6 compiles my usage of CTAD just fine!
