### ISSUE TITLE
Reduce the number of generated CI jobs

### ISSUE THREAD

**Issue by j-stephan** [alpaka-group/alpaka#1893]
After we abolished the 9 hand-written HIP jobs in favour of automatically generated jobs in #1889 I noticed today that this now spawns 43(!) HIP CI jobs. This seems a little excessive and we should reduce this to a more practical number.

**Comment by SimeonEhrig** [comment]
It HIP jobs will be automatically reduced if we add more compilers to the generator. At the moment, it generates so much HIP jobs, because it test also all possible pair combinations of CMake versions, Boost versions and C++ standards and the HIP compiler is the only available parameter for the host and device compiler.

Small example. The generator tries to test `CMake 3.19.8` with `Boost 1.75.0`, because the generator cares about, that each combination of two parameters exist. It does not care about if the device compiler is `hip`, `nvcc` or `clang` something else because this would be a third parameter. Therefore the generator will not add a job with `hip 5.1`+ `CMake 3.19.8` + `Boost 1.75.0`, if already `nvcc 11.6`+ `CMake 3.19.8` + `Boost 1.75.0` exist[1]. In practice it means each new value for a compiler increase the number of jobs less than it's successor until we reach a maximum number of (this number of jobs is enough to put in each possible combination of two parameters).

[1] If the generator want's to test `hip 5.1` with `boost 1.75.0` and `nvcc 11.6` with `boost 1.75.0` it is possible that the generator generate both jobs. It depends on the total number of combination of all values of all parameters.

**Comment by j-stephan** [comment]
Thanks for the explanation. The amount of jobs still seems quite high to me. We had about 6 or 7 CI stages before the merge, now we have 11. If I understand you correctly this number might still increase when adding the other compilers.

**Comment by SimeonEhrig** [comment]
Hard to say. We have a lot of hand written nvcc jobs. But it is possible, because I think the generator increases the test coverage. At the moment, our handwritten tests focus on the compiler combination. Testing different combinations of CMake, Boost and so one with the compilers happens by the way. Therefore I think we a big area of uncovered dependency tests, which will be covered by the generator. But don't forget, we want to also remove the Linux tests from GitHub Workflows.

**Comment by SimeonEhrig** [comment]
It's work in progress, but all combinations of nvcc (11.0-11.6) with gcc as host compiler ads only 7 jobs: https://gitlab.com/hzdr/crp/alpaka/-/pipelines/741922349

**Comment by j-stephan** [comment]
The GitLab CI now completes in ~30 minutes. That is acceptable.
