### ISSUE TITLE
Rework pitches

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#2083]
Pitches in alpaka are, IMO, suprising. Given the extents `{42, 10, 2}`, a 3D buffer of `float` (4 bytes) on the CPU has the following pitches: `{4, 3360, 80, 8}`. Yes, the pitch vector has 4 dimensions and this is actively used in the implementation of `ViewSubView`. 

The documentation of `getPitchBytes` says:

> The pitch in bytes. This is the distance in bytes between two consecutive elements in the given dimension.

Which is clearly wrong. Then, the implementation of `GetPitchBytes` says:

> This is the distance in bytes in the linear memory between two consecutive elements in the next higher dimension (TIdx-1).

Which is actually true (except for the 1 + highest dimension), but contradicts the documentation of `getPitchBytes`.

I strongly think the situation should be fixed. In my understanding, for the extent  `{42, 10, 2}`, the pitch vector should be `{80, 8, 4}`, and thus correspond to the documentation of `getPitchBytes`. However, such a change would be a silent breaking, since user code would still compile but have different behavior. But then, the function is already wrong wrt. to it's documentation, so such a change can also be seen as a fix. Alternativelty, `getPitchBytes` could be deprecated and replaced by a new function, like `getStrideBytes`, which has the correct behavior. Also, we could replace everything by a function `getPitchesInBytes` (see also #2049) that returns the proposed vector.

**Comment by fwyzard** [comment]
> Pitches in alpaka are, IMO, surprising.

Indeed!

> In my understanding, for the extent `{42, 10, 2}`, the pitch vector should be `{80, 8, 4}`,

IFF there is any use for the overall pitch `{3360, 80, 8, 4}` would also make more sense than the current `{4, 3360, 80, 8}`.
If there is no use for the overall pitch, `{80, 8, 4}` seems better.

**Comment by psychocoderHPC** [comment]
The pitch in alpaka is always the full pitch to jump to the next entry of the next dimension. `{4, 3360, 80, 8}` reduces the number of calculations because if you like to shift the view by `{0,1,0}` there is no need to touch the pitch for the dimension `x`.

That the pitch if a 3-dimensional buffer/view has 4 dimensions looks to me like a bug because in general if you do not need range checks the pitch only required 2 dimensions for a 3-dimensional buffer.

**Comment by fwyzard** [comment]
> the pitch only required 2 dimensions for a 3-dimensional buffer.

why only 2?

a subview in 3 dimensions may have a pitch in any of them, so wouldn't one need 3 values for the pitch?

**Comment by bernhardmgruber** [comment]
> The pitch in alpaka is always the full pitch to jump to the next entry of the next dimension.

Just to understand this. This means that for a 2D view, the 0-dim pitch is the number of bytes to go from one 1-dim element to the next 1-dim element?
And the number of bytes to go from one 0-dim element to the next is the size of the element type?

Such a model would work and require only  n-1 dimensions for the pitch vector, for an n-dimensional view. However, with this model we could never realize a sub view, that skips every 2nd element :) That would require us to have a pitch vector where the 0-dim pitch is the distance between elements in the 0-dim. This is how mdspan does it btw.

**Comment by fwyzard** [comment]
By the way, something else that could be useful is a flag that says if a buffer is contiguous or not: if it is contiguous, it can be `memcpy`ed with a single call.

**Comment by psychocoderHPC** [comment]
> a subview in 3 dimensions may have a pitch in any of them, so wouldn't one need 3 values for the pitch?

Since we know the type of elements we typically do not need to know how many bytes are required to go to the next elements.

Nevertheless in the current developer VC we came to the conclusion that the pitch array/vector should contain the zero dimension the bytes needed to go to the next element.
In our example of an buffer of float values with extents `{42, 10, 2}` and no padded lines pitchBytes should be `{80,8,4}`.
