### ISSUE TITLE
Support CUDA 12.4 and 12.5

### ISSUE THREAD

**Issue by SimeonEhrig** [alpaka-group/alpaka#2279]

**Comment by ichinii** [comment]
after updating to cuda 12.5 i get following error message when running my alpaka program:

`  what():  /home/ich/projects/rayx/Extern/alpaka/include/alpaka/mem/buf/uniformCudaHip/Copy.hpp(143) 'TApi::setDevice(m_iDstDevice)' A previous API call (not this one) set the error  : 'cudaErrorUnsupportedPtxVersion': 'the provided PTX was compiled with an unsupported toolchain.'!`

It is not clear to me where this error comes from and if this might be a issue that a future alpaka version would fix. Do you maybe have a guess?

At this point I am asking myself if it is expected, that new cuda versions will likely make alpaka applications unable to function correctly? In other words: Should one be aware of the alpaka cuda support, before updating cuda on a system?

**Comment by fwyzard** [comment]
what GPU are you compiling for ?

**Comment by psychocoderHPC** [comment]
@ichinii, please post the cmake command used to configure and compile.

Do you set `-DCMAKE_CUDA_ARCHITECTURES=52` where 52 is the sm level of your target GPU.

**Comment by psychocoderHPC** [comment]
https://forums.developer.nvidia.com/t/provided-ptx-was-compiled-with-an-unsupported-toolchain-error-using-cub/168292 is saying you have a driver and toolchain mismatch. 

- Do you compiled and executed the app on the same system?
- Do you have more than one CUDA SDK on the system?

Most most likely you missed to update you system driver.

**Comment by ichinii** [comment]
oh i am sorry. this is not an alpaka related issue. 

i noticed the problem first with an alpaka application, but turns out the issue also occurs in a little test setup, without alpaka.
sorry that i did not test and provide additional information. i was guessing that the issue was common among alpaka users.

i tried it on arch linux and manjaro. they possibly provide incompatible cuda and driver versions. both are up to date on my system. **downgrading cuda to 12.2 worked for me**.

still I answer the questions:

> @ichinii, please post the cmake command used to configure and compile.
> 
> Do you set `-DCMAKE_CUDA_ARCHITECTURES=52` where 52 is the sm level of your target GPU.
```
cmake \
    -DCMAKE_CXX_COMPILER=g++-13 \
    -DCMAKE_CUDA_ARCHITECTURES=52 \
    -Dalpaka_ACC_CPU_B_OMP2_T_SEQ_ENABLE:BOOL=ON \
    -Dalpaka_ACC_CPU_B_SEQ_T_SEQ_ENABLE:BOOL=ON \
    -Dalpaka_ACC_GPU_CUDA_ENABLE:BOOL=ON \
    -Dalpaka_RELOCATABLE_DEVICE_CODE:BOOL=ON \
    -G "Ninja" $PROJECT_DIR
```

>     * Do you compiled and executed the app on the same system?
yes
>     * Do you have more than one CUDA SDK on the system?
no
 
> Most most likely you missed to update you system driver.

afai can tell, the driver is up to date, in terms of what manjaro provides. Tho, this seems kind of odd to me. Because if driver version is an issue, then all cuda applications that were compiled with cuda 12.5 would require a very up2date driver. Does not seem very practical in terms of compatibility, to me.

Possibly the issue lies somewhere else. If I find it, I will post it here, for others that run into it.

anyways. sorry for relating this to alpaka and thanks for the quick response :)

**Comment by ichinii** [comment]
Oh I am sorry. Turns out the driver version does not catch up to the cuda version, although both were up to date on my manjaro system. Downgrading cuda to 12.3. works.

**Comment by psychocoderHPC** [comment]
I closed the issue, looks like it is solved

**Comment by psychocoderHPC** [comment]
I reponed it again, missed that the original issue is about updating the CI

**Comment by SimeonEhrig** [comment]
> At this point I am asking myself if it is expected, that new cuda versions will likely make alpaka applications unable to function correctly? In other words: Should one be aware of the alpaka cuda support, before updating cuda on a system?

@ichinii Yes, you should check the official supported CUDA version before you update. Otherwise you code could broke. Unfortunately it happens, that some new CUDA SDK versions introduces bugs, which we trigger in alpaka because we use complicated meta template programming. Normally this bugs are fixed in one of the next releases. But this means, we as alpaka developers needs to implement workarounds for specific CUDA versions.

But most of the time new CUDA SDK versions works out-of-the box. But be aware, if you use an unsupported CUDA version, maybe you need to implement workarounds by yourself.

**Comment by SimeonEhrig** [comment]
done during PR #2303
