### ISSUE TITLE
Add an OpenACC backend

### ISSUE THREAD

**Issue by bussmann** [alpaka-group/alpaka#248]
According to [this paper on the Sunway Taihulight](http://www.netlib.org/utk/people/JackDongarra/PAPERS/sunway-report-2016.pdf), the new Chinese HPC system that topped the TOP 500 at ISC'2016 uses a custom OpenACC implementation. So, in order to use it we would surely need an OpenACC backend. How much work would that be and can work be copied from the OpenMP 4 implementation?

**Comment by BenjaminW3** [comment]
As gcc 6.1 supports OpenACC 2.0a we have already support for a OpenACC capable compiler and do not need to add e.g. the PGI compiler (especially the integration into the CI could be problematic). => Nothing to do
Is there any information about the compiler they use?
I do not have any information and have not searched for it, but I expect it to be a non-offloading many-core CPU. This would allow an implementation very similar to our current OpenMP implementation, as it does not support offloading either, because we directly use host allocated memory within OpenMP regions => OpenMP adaption should be possible.
Is this non-offloading assumption true?

**Comment by erikzenker** [comment]
I saw today updated slides about the software stack supported by the sunway taihulight on the isc. Next to OpenAcc there was also OpenMP and MPI 3.0 mentioned. Nevertheless, the speaker only mentioned porting efforts to OpenAcc.

There were no information about the supported compilers, used operating system or the architecture of the processor yet. But I think such information will follow soon.

**Comment by ax3l** [comment]
Update: According to our latest meeting and information from @juckel, the chinese machines around Sunway Taihulight is moving away from OpenACC :'-S

**Comment by j-stephan** [comment]
If I'm not mistaken we should be able to close this. @jkelling introduced OpenACC support with #1127.

**Comment by psychocoderHPC** [comment]
> If I'm not mistaken we should be able to close this. @jkelling introduced OpenACC support with #1127.

Yes I think so, I will close it.

**Comment by psychocoderHPC** [comment]
implemented with #1127
