### ISSUE TITLE
Travis GitHub Marketplace

### ISSUE THREAD

**Issue by ax3l** [alpaka-group/alpaka#497]
@BenjaminW3 I recently authorized Travis CI already for the new GitHub marketplace (`travis-ci`). Do you need `travis-pro` as well? We got that you requested access for it yesterday, but I think it's a mismatch.

**Comment by BenjaminW3** [comment]
I have tried to enable the new Pull Request checks view but I may simply have clicked the wrong button ;-)

**Comment by ax3l** [comment]
Ok :D

**Comment by BenjaminW3** [comment]
I have reopened the issue because we still might want to enable this.
Travis is integrating with the github checks API: https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com
For this to work, all repositories will gradiually be moved from travis-ci.org to travis-ci.com (opt-in for now): https://docs.travis-ci.com/user/open-source-on-travis-ci-com

**Comment by ax3l** [comment]
All right, so let us keep this open and ping me when we shall start the transition (or I ping here if we move the whole organization). problem is, I can only activate this organization-wide at once for all repos.

**Comment by SimeonEhrig** [comment]
@BenjaminW3 I think, we can close the issue, because we have completely moved to GitHub Actions.
