### ISSUE TITLE
Compiler Explorer

### ISSUE THREAD

**Issue by ax3l** [alpaka-group/alpaka#600]
We should add `alpaka/develop` to the libs of Matt Godbolt's compiler explorer: https://godbolt.org/

https://github.com/mattgodbolt/compiler-explorer/wiki/Installed-libraries

Relevant files:
- https://github.com/mattgodbolt/compiler-explorer-image/blob/master/update_compilers/install_libraries.sh
- https://github.com/mattgodbolt/compiler-explorer/blob/master/etc/config/c++.amazon.properties

Example PRs:
- https://github.com/mattgodbolt/compiler-explorer/pull/834
- https://github.com/mattgodbolt/compiler-explorer-image/pull/69

Needs probably simplified headers: see #601

**Comment by BenjaminW3** [comment]
[Example project](https://github.com/loopperfect/conduit) using [godbolt as playground](https://godbolt.org/z/wTRcvK)

**Comment by bernhardmgruber** [comment]
I am solving this in LLAMA by creating an amalgamated (single header) llama.hpp on each commit to develop and commit that file to an orphaned branch. That is similar to what we do for github pages. See: https://github.com/alpaka-group/llama#single-header

**Comment by SimeonEhrig** [comment]
@bernhardmgruber Does the llama header also include alpaka? I also plan to create a single header version for vikunja and I need to resolve this dependency.

**Comment by bernhardmgruber** [comment]
@SimeonEhrig no, because llama does not depend on alpaka. llama also depends on Boost, and I do not include that. But fortunately, you can just have Boost on compiler explorer with a few clicks. Since vikunja depends on alpaka, I think we would really need to add this to Compiler Explorer as suggested.

**Comment by bernhardmgruber** [comment]
We have a single header of alpaka now that can be used on godbolt: https://github.com/alpaka-group/alpaka#single-header

I don't think we need alpaka on godbolt directly, since this way we can only have released versions of alpaka, which are scarce and often lag behind tremendously in features. I think most users (and also us devs) want to play with the develop branch on godbolt, or even be able to choose a specific commit to use.

**Comment by j-stephan** [comment]
Closing as completed.
