### ISSUE TITLE
Coroutine based accelerator backend

### ISSUE THREAD

**Issue by BenjaminW3** [alpaka-group/alpaka#689]
We should investigate into adding a coroutine based backend.
It should be similar to the fiber based backend (cooperative multitasking within a block, possibly mutlithreaded block execution).
Coroutines are supported by clang 5+ and MSVC but not yet in gcc. It might not be possible to compile them with NVCC.
Clang requires `-fcoroutines-ts -stdlib=libc++` to get this fun started ;-)
MSVC requires `/await` and optionally `/await:heapelide` /std:c++latest /Zc:__cplusplus

**Comment by BenjaminW3** [comment]
After investigating it a bit more, it might be hard to use coroutines as described in the current draft without major changes to alpaka.
There are multiple things that would have to be changed. All the functions that could eventually even transitively lead to a suspension point (synchronization function) would have to be called with `co_await` and return an object that is `Awaitable`. This would apply to the alpaka library functions for synchronization but also to all intermediate user provided functions in the call-stack as well as the base kernel function object itself.
Even those two limitations would result in the addition of at least two new macros. Furthermore, the coroutines backend could not be enabled together with any other backend.

**Comment by bernhardmgruber** [comment]
What is the motivation for adding a coroutine based backend? Coroutines are not a tool for parallel execution, so I do not see why they fit into alpaka.

As observed in the second comment, coroutines can enable really interesting workflows, but that will also lead to wholly different  API designs. Still, the focus of coroutines is asynchronity via suspension and resumption outside the context of threading. So we would still need threads again to gain parallelity.

**Comment by j-stephan** [comment]
@BenjaminW3 Do you still think we should investigate this?

**Comment by BenjaminW3** [comment]
> What is the motivation for adding a coroutine based backend? Coroutines are not a tool for parallel execution, so I do not see why they fit into alpaka.

For me alpaka is not only about parallel execution in the sense of multiple OS/hardware threads.
It is about exploiting the available hardware (computation units and memory) as much as possible by mapping the abstraction layers onto what is available on a specific machine.
It may or may not be much more efficient (especially cache efficient), if multiple kernels would run in a lockstep-like way on a single thread/core. We already have one such implementation that uses fibers which is very similar to what coroutines might be able to achieve.

> Do you still think we should investigate this?

I am still interested in this topic.

**Comment by bernhardmgruber** [comment]
> I am still interested in this topic.

I am eagerly looking forward to a PR and some benchmarks then :)

**Comment by bussmann** [comment]
I like Benjamin's answer on the scope of Alpaka!

**Comment by bernhardmgruber** [comment]
We discussed this issue again today during the alpaka VC as part of the discussion around removing the Fiber backend. We see a benefit in pursuing a coroutine based backend to allow e.g. to have multiple threads to execute multiple blocks in parallel, but have a single hardware thread per block and still have multiple alpaka threads inside a block. This is currently not possible in our backends as e.g. the `ACC_CPU_B_OMP2_T_SEQ` backend requires a single thread per block. The issue there is that if you have thread synchronization primitives, like `syncBlockThreads()` you would need to be able to suspend alpaka threads until all threads in a block arrive at the synchronization primitive. Since coroutines are resumeable, they naturally allow such a behavior.

**Comment by fwyzard** [comment]
> to have multiple threads to execute multiple blocks in parallel, but have a single hardware thread per block and still have multiple alpaka threads inside a block.

isn't this exactly what the Fibers backend is supposed to do ?

**Comment by j-stephan** [comment]
> isn't this exactly what the Fibers backend is supposed to do ?

Yes, Coroutines and Boost.fiber are quite similar. However, three of our developers failed to set up the Fiber back-end to do something useful (which is why we have now decided on removing it instead of investing any more time). On top of that it is another (although optional) Boost dependency which we don't like.

Coroutines have the benefit of being a standard C++ feature. So we want to keep this kind of execution in mind for a future back-end but it is currently low on our priority list.

**Comment by fwyzard** [comment]
This is off-topic here, but still:

> On top of that it is another (although optional) Boost dependency which we don't like.

I really find it ... disarming, for lack of a better word, how much you dislike having dependencies on boost (or anything else, for that matter).

As a user, I would prefer to have at least the option for using features provided by third-party libraries that have been tested over the years (and I am using anyway) instead of a local reimplementation.

**Comment by j-stephan** [comment]
> I really find it ... disarming, for lack of a better word, how much you dislike having dependencies on boost (or anything else, for that matter).

That mostly affects Boost (because of the reasons listed below) because it is the only core/runtime dependency we always require. I'm not aware of any other dependency we refused but I may be forgetting something. In general, alpaka is intended to be as header-only as possible, ideally without introducing any dependencies besides the individual back-end requirements.

> As a user, I would prefer to have at least the option for using features provided by third-party libraries that have been tested over the years

Unfortunately we do not share that appraisal. Whenever we try new compilers or HPC systems Boost is a common point of failure because a) the libraries are not as well tested as one would assume or b) HPC modules are notoriously out of date and/or wrongly configured. See (for example) Boost.fiber which in its current stable version doesn't work together with a C++ standard that is two years old.

**Comment by fwyzard** [comment]
Sorry but this sounds like a massive contradiction: if "HPC modules are notoriously out of date", why do you care so much about "a C++ standard that is two years old" (_i.e._ c++20) which so far is not fully supported by any complier (nor by CUDA) ?

**Comment by fwyzard** [comment]
Also, when you say "Boost is a common point of failure" -- is the problem really with Boost, or with how CMake is (mis)configured to pick it up ?

**Comment by fwyzard** [comment]
> I'm not aware of any other dependency we refused

Sorry, then it was maybe my wrong assumption that you prefer to avoid dependencies.

If that is not the case, you could look into adding Intel TBB as a full dependency, in order to use the various concurrent containers it provides.

**Comment by fwyzard** [comment]
Anyway, trying to get back on-topic and to provide some constructive feedback, I'll copy here https://github.com/alpaka-group/alpaka/issues/1714#issuecomment-1128719434:

> Is it correct that Fibers is the only single-thread CPU backend that supports thread-level synchronization primitives, like `syncBlockThreads()` ?
> 
> If that is the case, could you keep the (optional) Fibers back-end in Alpaka until an eventual Coroutine-based back-end is available ?

**Comment by BenjaminW3** [comment]
I second the request of @fwyzard.
We should try to keep the fiber based backend in there as long as technically possible until we have a reasonabe replacement.
It may only be of academic relevance, but it is a good starting point for similar experiments.

**Comment by j-stephan** [comment]
> if "HPC modules are notoriously out of date" why do you care so much about "a C++ standard that is two years old" (i.e. c++20) which so far is not fully supported by any complier (nor by CUDA) ?

Those are two separate issues. One is "Boost is not as well tested as we would like" and the other is "HPC modules are often outdated, misconfigured, not present on all nodes, etc.". Both add to our critical view.

> Also, when you say "Boost is a common point of failure" -- is the problem really with Boost, or with how CMake is (mis)configured to pick it up ?

CMake just looks up the headers and libraries and then provides the relevant flags to the compiler. If Boost is too old, not present or doesn't work with a recent C++ standard this cannot be solved with CMake.

> Sorry, then it was maybe my wrong assumption that you prefer to avoid dependencies.

We are reluctant to do so, but not entirely opposed. We accepted your `atomic_ref` PR, for example.

**Comment by j-stephan** [comment]
Also, if we want to discuss Boost specifically, please continue here: #481.

**Comment by bernhardmgruber** [comment]
The idea of a coroutine based backend stuck with me and since I also need to learn a bit about coroutines I gave it a shot today. However, I got stuck in a problem that I could not solve in a few hours. Maybe someone of you has a solution.

I tried to create a backend similar to the fiber backend, where blocks execute serially. Threads within a block would execute serially as well, but as soon as a synchronization primitive is encountered, the thread suspends and the next thread continues until all threads have reached the synchronization point. This would be an advantage over the serial backend, which only allows a single thread per block.

The central problem is now how to transfer control from the synchronization point (a specialization of `SyncBlockThreads`) to the `TaskKernelCpu::operator()` without affecting usercode. Here is a sketch:

```c++
... syncThreads(Acc& acc) {
    co_await ...; // need to suspend and transfer control to launchKernel, without unwinding stack (i.e. not return to userKernelFunc)
}

void userKernelFunc(Acc& acc) { // void return type
    std::cout << "kernelFunc 1" << std::endl;
    syncThreads(acc);
    std::cout << "kernelFunc 2" << std::endl;
    syncThreads(acc);
    std::cout << "kernelFunc 3" << std::endl;
}

auto launchKernel(Acc& acc) { // promise type should initially suspend (lazy coroutine)
    userKernelFunc(acc);
    co_return;
}

// called from TaskKernelCpu::operator()
void executeBlock() {
    for each thread in block {
        Acc acc = ...;
        launchKernel(acc);
    }
    for each coroutine handle ch of each thread in block {
        while(!ch .done())
            ch .resume();
        coroutineHandle.destroy();
    }
}
```

We need to stop execution of the kernel thread inside `syncThreads`. After reading through some tutorials, I believe the only supported way is to use `co_await`. But so far `co_await` always returned from `syncThreads` and continued execution of `userKernelFunc`. I could not make it jump back into `launchKernel` directly.

Here is something to play: https://godbolt.org/z/56ThP1W1o

**Comment by bernhardmgruber** [comment]
Using [symmetric transfer](https://lewissbaker.github.io/#:~:text=C%2B%2B%20Coroutines%3A%20Understanding%20Symmetric%20Transfer,consuming%20any%20additional%20stack-space.) I could get a step further by making a thread's corouting transfer to the next thread in the block upon a synchronization primitive. The last thread in the block would then resume the coroutine of the first thread after the synchronization primitive. However, that also crashes here and there, because I have not found a way to pass a thread's coroutine promise into the synchronization primitive implementation and use it there in a `co_await` expression.

Anyway, I will pause here again, because I don't have much time to spend and it seems there are a few more obstacles to overcome. Here is what I have: https://github.com/bernhardmgruber/alpaka/tree/coroutine

**Comment by bernhardmgruber** [comment]
I have been talking to a few friends about this and one suggestion was to have each alpaka device function that could contain a synchronization primitive have a return type depending on the accelerator type:

```c++
template <typename Acc>
auto foo(Acc acc) -> Ret<Acc> { ... }

template <typename Acc>
auto bar(Acc acc) -> Ret<Acc, T> { ... }
```

Then for the coroutine backend we could make this return type a coroutine type and otherwise just turn `Ret<Acc>` into `void` and `Ret<Acc, T>` into `T`.

This is very invasive though.

**Comment by bernhardmgruber** [comment]
After reading a good explanation of coroutine stack handling in Fedor Pikus' book The Art of Writing Efficient Programs, I reach the conclusion that C++ coroutines cannot be used in alpaka the same way Boost.Fiber can. The reason is that C++ coroutines are stackless, vs. Boost.Fiber which uses stackful coroutines. This has the following implication:

Stackless coroutines allocate their coroutine frame on the heap. This is the first stack frame so to speak. Every further function call places their stack frame on the *resuming thread's callstack*. So the moment you call a non-coroutine function from a coroutine, you are back in normal function calling land. Now, if you would reach a synchronization primitive in alpaka and you would want to yield from the coroutine, you can't because you are inside an ordinary function. You would need to return from the entire call chain back to the coroutine frame and can only yield from there. In order to yield from within the synchronization primitive, *every* function between the kernel launch and the synchronization primitive, including all user code, needs to be a coroutine. Alpaka's `syncThreads` would need to return a coroutine type, which would need to be `co_yield`ed through the entire callchain, always. So effectively, the entire device code must be coroutines and use coroutine types as return types and `co_yield` at EVERY function call.

This is a gigantic implication for user code. User code would e.g. no longer be able to use normal return types, since we need the return types for the coroutine logic. Furthermore, *every* function call in device code would imply a heap allocation of the coroutine frame, which can be ellided by the compiler, but it is not guaranteed. Also, coroutines are e.g. not supported by CUDA in device code, so we would need to come up with a workaround to switch the *entire* device code between coroutines and ordinary functions depending on the backend.

I firmly believe the engineering cost to achieve such a piece of black magic is unpayable for our team and probably also for our users.

**Comment by fwyzard** [comment]
> I firmly believe the engineering cost to achieve such a piece of black magic is unpayable for our team and probably also for our users.

I agree on the users' side.

**Comment by j-stephan** [comment]
So, judging by the likes and the follow-up comment I assume we have the following consensus: No coroutine back-end (at least with C++20 coroutines, who knows what will change in the future) and instead we keep Boost.Fiber. Are there opposing views?

**Comment by fwyzard** [comment]
No objections from my side...

Just FYI, at some point I might be interested in looking at [argobots](https://www.argobots.org/) and its C++ wrapper, [Thallium](https://mochi.readthedocs.io/en/latest/thallium.html) as an alternative to Boost.Fiber .

**Comment by bernhardmgruber** [comment]
> So, judging by the likes and the follow-up comment I assume we have the following consensus: No coroutine back-end (at least with C++20 coroutines, who knows what will change in the future) and instead we keep Boost.Fiber. Are there opposing views?

I was just arguing against a C++20 coroutine based backend. I never argued to keep Boost.Fiber. In fact, I am still firmly in favor of its removal.

> Just FYI, at some point I might be interested in looking at [argobots](https://www.argobots.org/) and its C++ wrapper, [Thallium](https://mochi.readthedocs.io/en/latest/thallium.html) as an alternative to Boost.Fiber .

PR welcome! :)

**Comment by j-stephan** [comment]
> I was just arguing against a C++20 coroutine based backend. I never argued to keep Boost.Fiber. In fact, I am still firmly in favor of its removal.

Yes, I was taking the discussion around Boost.Fiber into account when making that comment. IIRC we decided to keep it for the time being.

**Comment by bernhardmgruber** [comment]
Anyway. Can we close this issue then?

**Comment by j-stephan** [comment]
If anyone feels this needs more discussion, feel free to reopen (or ping me if you're missing the necessary maintainer powers).
