### ISSUE TITLE
Thread sanitizer remark

### ISSUE THREAD

**Issue by krzikalla** [alpaka-group/alpaka#768]
Starting at alpaka-0.3.5/include/alpaka/stream/StreamCpuSync.hpp:177 we have:

  stream.m_spStreamImpl->m_bCurrentlyExecutingTask = true;
  task();
  stream.m_spStreamImpl->m_bCurrentlyExecutingTask = false;

If the enqueue() is called by multiple threads for the same stream, then the reads and writes to m_bCurrentlyExecutingTask are racing, since m_spStreamImpl is shared. I don't know what this variable is for beside the empty()-call below, but whatever it is, it won't work.

**Comment by BenjaminW3** [comment]
You are right that this will not work when called from multiple threads.
However, most parts/objects in alpaka are not written in a way that a single object can safely be used from multiple host threads. This is only one of many issues.
Is it valid and safe to use e.g. a cudaStream (or other CUDA objects) in parallel from multiple host threads?

**Comment by krzikalla** [comment]
No, for CUDA streams it is generally not really working (the problem is, that then multiple cuda streams are started working on the same data). Thatswhy we have guarded that enqueue() with omp single.
However, with one of the recent changes the usage of multiple threads became actually possible, so that alpaka doesn't enforce fork-join on the cpu anymore (which is a huge step forward btw). We should not step back here, but try to fix the issues.

**Comment by BenjaminW3** [comment]
What do you think would be the correct solution?
We have the following constraints:
* A stream can only ever execute one task at a time
* A synchronous stream (here `StreamCpuSync`) blocks the calling thread until the task has been finished

Even without the usage of the `m_bCurrentlyExecutingTask` variable a concurrent usage of a single `StreamCpuSync` would not comply to the rules because it should never execute two tasks at the same time.
We have not yet expected concurrent access to a stream. If we really want to enable this, we would have to add a mutex for the `StreamCpuSync` and guard the whole code block above with a lock.

**Comment by krzikalla** [comment]
I am not sure, how executors and streams (queues) interact, but for StreamCpuSync your first constraint doesn't hold, since the operator() in ExecCpuOmp2Blocks  checks, whether it is already called from a parallel region (which in turn can mean, that more than one Enqueue was called on the same stream by multiple threads. 

I am not even sure, if and how the change made in https://github.com/ComputationalRadiationPhysics/alpaka/pull/666 would work with StreamCpuASync.

**Comment by BenjaminW3** [comment]
> I am not even sure, if and how the change made in #666 would work with StreamCpuASync.

I am not sure what you mean. The difference between a `StreamCpuAsync` and a `StreamCpuSync` executing a kernel via `CpuOmp2Blocks` is the extra thread which `StreamCpuAsync` uses.
* In the case of `StreamCpuAsync`, the kernel task is always executed by a `std::thread` which has nothing to do with an OpenMP thread, so there will be no special handling and new OpenMP threads will be spawned to execute the kernel.
* In the case of `StreamCpuSync`, the kernel task is directly executed in the calling thread which may or may not be within a OpenMP parallel region. If not, new OpenMP threads will be spawned, else it will reuse the existing parallel region.

#666 was implemented on request and I am not yet sure how this is used in practice and am sceptical if it is useful at all. When the OpenMP parallel region has `n` threads (expecially `n>1`), then this would result in enqueuing the kernel task `n` times where all of those kernel tasks are executed in parallel (because there is no mutex around the place this tickets is about) and all kernel executions would share the `n` OpenMP threads. This is most probably not what you want.
Pseudo code:
```
Stream queue;
#pragma omp parallel num_threads(4)
{
    enqueue(queue, kernelTask);
// StreamCpuSync: kernelTask is executed 4 times and possibly in parallel and with a number of threads I would not bet on.
// StreamCpuAsync: kernelTask is executed 4 times one after each other with a deterministic number of OpenMP threads (independent of the 4 of this region).
}
```
With the fix I proposed (`mutex` in `StreamCpuSync`) the `StreamCpuSync` will have the same behaviour as `StreamCpuAsync`.

**Comment by psychocoderHPC** [comment]
> With the fix I proposed (mutex in StreamCpuSync) the StreamCpuSync will have the same behavior as StreamCpuAsync.

Do you suggest a mutex per stream?

**Comment by BenjaminW3** [comment]
Yes, a `mutex` per `StreamCpuSync` so that it behaves correctly even when it is called from multiple threads. The `StreamCpuAsync` already has a `mutex` in the `ThreadSafeQueue` which is used and should work correctly when called from different threads.

**Comment by krzikalla** [comment]
Nonono, no mutexes. The idea of #666 was to reuse threads in Enqueue instead of spawning new ones every time and use "omp single" around the Enqueue (whic was a measurable performance loss). I understand, that forcing a StreamCpuSync to execute tasks sequential makes for a clean semantic. However, currently this would break our code performance-wise. We need another saolution.
Our use case is as follows:
1. If a device is present, then one OpenMP thread calls enqueue on the device stream. Currently we use "omp single" for the enqueue and synchronous device streams, so everything is in order. The question remains, how we would implement an asynchronous handling using "omp single nowait" and async device streams. Can every thread use alpaka::wait::wait for device streams?

2. If no device is present, then all OpenMP threads calls enqueue on the cpu stream. The StreamCpuSync implementation doesn't spawn new threads in that case, but reuses the existing one. **This feature should remain in Alpaka.** 
I guess we won't care about StreamCpuASync, since we already reuse our threads, but for StreamCpuSync (or whatever new stream we will have) we should be able to wait, that no thread is executing a task of that stream.

**Comment by psychocoderHPC** [comment]
@krzikalla Could you please have a look to #786. It is already merged but if I understand your description correct this should be what you mean.

What do you mean by `If a device is present`? You always have a device in alpaka else you cannot compute.

**Comment by psychocoderHPC** [comment]
> 1. Can every thread use alpaka::wait::wait for device streams?

As I know it should not be an issue but to be sure let's wait for @BenjaminW3's answer.

[update] We need to check it for CUDA and HIP. Since we are using the CUDA runtime API it could be it is not allowed to access streams those are created by another thread.

**Comment by krzikalla** [comment]
#786 might fix the problem described here, but it creates an even bigger one: now tasks, that should execute in parallel, are executed sequential. Please, do not roll out #786.

**Comment by BenjaminW3** [comment]
In a meeting last week we decided to rename `QueueCpuSync` and `QueueCpuAsync` to `QueueCpuBlocking` and `QueueCpuNonBlocking` because this is what they are really meant to be. The one blocks the caller when something is enqueued and the other not. However, those queues are explicitly meant to execute one task after the other and never in parallel. If you want to execute something in parallel, you have to use multiple queues. There is no implicit synchronization between queues. 

> Can every thread use alpaka::wait::wait for device streams?

Yes, this should be possible.

**Comment by psychocoderHPC** [comment]
@krzikalla Could you maybe call me at work. I have problems to understand your workflow. I think we can shortcut the discussion via a phone call.
