### ISSUE TITLE
Synchronous queue wait in multi threaded environment

### ISSUE THREAD

**Issue by psychocoderHPC** [alpaka-group/alpaka#791]
Queues in alpaka are always asynchronous to each other. In the [CPU device object](https://github.com/ComputationalRadiationPhysics/alpaka/blob/6b42f89204a6800a926b36f07d8fd2908892378e/include/alpaka/dev/DevCpu.hpp#L79-L115) we collect all asynchronous queues to allow synchronization later if [wait()](https://github.com/ComputationalRadiationPhysics/alpaka/blob/6b42f89204a6800a926b36f07d8fd2908892378e/include/alpaka/dev/cpu/Wait.hpp#L34-L59) on a device is called.  

Since we added/fixed multi-thread support for synchronous queues in #786 we need the same mechanism for synchronous queues because a synchronous queue is only blocking the caller thread and the execution in one queue.

I need the same registration mechanism for we use for asynchronous queues also for a new special OMPQueue.

CC-ing: @BenjaminW3, do you have any suggestions? I currently evaluate if we can solve this issue if we create an interface class for queues and register the interfaces in the device.

**Comment by psychocoderHPC** [comment]
I am currently working on this issue. 
During my refactoring, I found a few more places which break the thread safety of alpaka.

**Comment by BenjaminW3** [comment]
An `ICpuQueue` interface with some virtual abstract methods might work. We would have to sepecialize the event enqueue method for ICpuQueue in this case.
In contrast to all other parts of alpaka this would have a runtime overhead due to a virtual function call.
A simpler solution for this problem would be to add another list to the `DevCpu` for blocking queues and iterate over this list separately. This would not make the code better but it would be as good as the current solution.

**Comment by psychocoderHPC** [comment]
I will come up first with two different queues within the dev object. This is something we can later refactor.
I will open the PR today.

**Comment by psychocoderHPC** [comment]
#797 is fixing that the Blocking queue is not taken into account in wait operation
