### ISSUE TITLE
HIP(HCC) queue and time test failures

### ISSUE THREAD

**Issue by tdd11235813** [alpaka-group/alpaka#794]
- compiling time test fails for `--amdgpu-target=gfx701` (just remove it in alpakaConfig.cmake)
- queue test `queueShouldNotExecuteTasksInParallel` fails at runtime (tested on AMD RX Vega64, fwk388)

```zsh
-------------------------------------------------------------------------------
queueShouldNotExecuteTasksInParallel
-------------------------------------------------------------------------------
/alpaka/test/unit/queue/src//QueueTest.cpp:184
...............................................................................

/alpaka/test/unit/queue/src//QueueTest.cpp:132: FAILED:
  CHECK( !taskIsExecuting.exchange(true) )
with expansion:
  false

/alpaka/test/unit/queue/src//QueueTest.cpp:134: FAILED:
  CHECK( taskIsExecuting.exchange(false) )
with expansion:
  false

/alpaka/test/unit/queue/src//QueueTest.cpp:144: FAILED:
  CHECK( !taskIsExecuting.exchange(true) )
with expansion:
  false

/alpaka/test/unit/queue/src//QueueTest.cpp:146: FAILED:
  CHECK( taskIsExecuting.exchange(false) )
with expansion:
  false

===============================================================================
test cases:  5 |  4 passed | 1 failed
assertions: 40 | 36 passed | 4 failed
```

**Comment by BenjaminW3** [comment]
My first thought about the failing test was that the HIP queue might execute the host callbacks we use for verification in parallel. However, this can not be the case and there has to be a much harder error somewhere.
This test has a global variable `taskIsExecuting` wich is initially false. Then we enqueue two equal tasks which check and exchange the `taskIsExecuting` value they hold by reference on entry and exist. Logically the entry test of one of the two tasks has to succeed because the initial value was `false` and `taskIsExecuting` is a `std::atomic`. There is no way in which both entry checks could ever fail even when executed in non-deterministic order or in parallel.
So my conclusion is that this is more likely a compilation issue in some kind.
When we set some trust into the order of the errors being printed (which is somehow risky because the code was possibly executed in parallel), we can believe that the tasks were executed in order `task1`->`task2` and not in parallel. It looks like all the checks reported exactly the opposite of what they were expected to do. Maybe the HIP compilation adds some random `!` in the code? ;-)

**Comment by psychocoderHPC** [comment]
The comment from @BenjaminW3  should be taken into account: https://github.com/ComputationalRadiationPhysics/alpaka/pull/800#discussion_r300050075

**Comment by tdd11235813** [comment]
opened HIP [issue](https://github.com/ROCm-Developer-Tools/HIP/issues/1205).

**Comment by psychocoderHPC** [comment]
It could be https://github.com/ROCm-Developer-Tools/HIP/pull/1674 is solving the issue. I reverted the workaround in alpaka and activated the corresponding queue tests. It looks like at least with HIP-clang is all working. I will create a PR soon.

**Comment by psychocoderHPC** [comment]
@tdd11235813 Could you please create a mini app to reproduce the behavior. As you found out it looks like it is not fixed :-(

**Comment by tdd11235813** [comment]
the mini-app is already on our internal ToDo list for AMD, I schedule this one, but it will not happen this week.

**Comment by tdd11235813** [comment]
reproducible is provided in the corresponding HIP [issue](https://github.com/ROCm-Developer-Tools/HIP/issues/1205). Issues could be reproduced without Alpaka.
