### ISSUE TITLE
CUDA no extended lambda under windows enabled

### ISSUE THREAD

**Issue by psychocoderHPC** [alpaka-group/alpaka#826]
We are currently not enabling extended lambda support for CUDA under windows `--expt-extended-lambda`
Therefore #822 is not passing the CI https://travis-ci.org/ComputationalRadiationPhysics/alpaka/jobs/574760423#L3854

**Comment by BenjaminW3** [comment]
The build you linked fails because it tests the support for explicitly setting `ALPAKA_CUDA_NVCC_EXPT_EXTENDED_LAMBDA=OFF`.
alpaka does not yet enforce enabling `--expt-extended-lambda`.

The two windows builds seem to have this enabled but fail with `CollectiveQueue.cpp(57): error : On Windows, the enclosing parent function ("____C_A_T_C_H____T_E_S_T____0") for an extended __host__ __device__ lambda cannot have internal or no linkage`.

**Comment by BenjaminW3** [comment]
As a fast workaround for your PR to get 0.4.0 out of the door, you could simply use a `struct` instead of the lambda.

**Comment by psychocoderHPC** [comment]
Yes I also thought to switch to a struct to be independent of possible other PRs.

**Comment by BenjaminW3** [comment]
Do you really want to do something here? As described the first "issue" is by-design and the windows linkage issue was a problem in the user code.

**Comment by psychocoderHPC** [comment]
I will close this PR. As suggested I used a struct instead of a lambda function.
