### ISSUE TITLE
BufCpu constructor error

### ISSUE THREAD

**Issue by waredjeb** [alpaka-group/alpaka#883]
Hello,
I have some trouble writing a class. The class is the following:
```
#include <iostream>
#include <alpaka/standalone/CpuSerial.hpp>
#include <alpaka/alpaka.hpp> 

using Dim = alpaka::dim::DimInt<1u>;
using Idx = std::size_t;
using Acc = alpaka::acc::AccCpuSerial<Dim,Idx>;
using DevAcc = alpaka::dev::Dev<Acc>;
using DevHost = alpaka::dev::DevCpu;
using PltfAcc = alpaka::pltf::Pltf<DevAcc>; //Platform specific
using PltfHost = alpaka::pltf::Pltf<DevHost>; //Platform specific
using Queue = alpaka::queue::QueueCpuSync;

DevAcc const devAcc(alpaka::pltf::getDevByIdx<PltfAcc>(0u));

class myClass{

  class myStruct{
    int x,y
    float fx,fy;
  };

   using TBufH = alpaka::mem::buf::Buf<DevHost, myStruct, Dim, Idx>; 
   using TBufD = alpaka::mem::buf::Buf<DevAcc, myStruct, Dim, Idx>;

   myClass() = default;
   myClass(TBufH data_h, Queue queue)
   {
   data_d_ = alpaka::mem::buf::alloc<myStrct, Idx>(devAcc, sizeof(myStruct));
   alpaka::mem::view::copy(queue, data_h, data_d_, sizeof(myStruct));
   }

   private:
     TBufD data_d_;
};
```
 I got this error with the BufCpu constructor. 
```
 In constructor 'myClass::myClass(myClass::TBufH, Queue)':
class.h:37:39: error: no matching function for call to 'alpaka::mem::buf::BufCpu<myClass::myStruct, std::integral_constant<long unsigned int, 1>, long unsigned int>::BufCpu()'
     myClass(TBufH data_h, Queue queue){
                                       ^
In file included from /data/user/wredjeb/cupla/alpaka/include/alpaka/alpaka.hpp:143,
                 from class.h:3,
                 from main.cc:4:
/data/user/wredjeb/cupla/alpaka/include/alpaka/mem/buf/BufCpu.hpp:158:4: note: candidate: 'alpaka::mem::buf::BufCpu<TElem, TDim, TIdx>::BufCpu(alpaka::mem::buf::BufCpu<TElem, TDim, TIdx>&&) [with TElem = myClass::myStruct; TDim = std::integral_constant<long unsigned int, 1>; TIdx = long unsigned int]'
    BufCpu(BufCpu &&) = default;
    ^~~~~~
/data/user/wredjeb/cupla/alpaka/include/alpaka/mem/buf/BufCpu.hpp:158:4: note:   candidate expects 1 argument, 0 provided
/data/user/wredjeb/cupla/alpaka/include/alpaka/mem/buf/BufCpu.hpp:156:4: note: candidate: 'alpaka::mem::buf::BufCpu<TElem, TDim, TIdx>::BufCpu(const alpaka::mem::buf::BufCpu<TElem, TDim, TIdx>&) [with TElem = myClass::myStruct; TDim = std::integral_constant<long unsigned int, 1>; TIdx = long unsigned int]'
    BufCpu(BufCpu const &) = default;
    ^~~~~~
/data/user/wredjeb/cupla/alpaka/include/alpaka/mem/buf/BufCpu.hpp:156:4: note:   candidate expects 1 argument, 0 provided
/data/user/wredjeb/cupla/alpaka/include/alpaka/mem/buf/BufCpu.hpp:149:19: note: candidate: 'template<class TExtent> alpaka::mem::buf::BufCpu<TElem, TDim, TIdx>::BufCpu(const alpaka::dev::DevCpu&, const TExtent&)'
    ALPAKA_FN_HOST BufCpu(
                   ^~~~~~
/data/user/wredjeb/cupla/alpaka/include/alpaka/mem/buf/BufCpu.hpp:149:19: note:   template argument deduction/substitution failed:
In file included from main.cc:4:
class.h:37:39: note:   candidate expects 2 arguments, 0 provided
     myClass(TBufH data_h, Queue queue){

```
So, the problem seems clear, BufCpu doesn't have the default constructor. But, is there a way to solve it?

**Comment by sbastrakov** [comment]
@waredjeb yes, so the buffer classes do not have default constructors. I guess you can use one of the standard ways to overcome it:

- Construct this member in the initializer list. This is kinda how we do it in the [examples](https://github.com/ComputationalRadiationPhysics/alpaka/blob/a21ac3e5d83a21a3ed007aa399ea16f1e8d0f994/example/bufferCopy/src/bufferCopy.cpp#L194). Ofc in your application the context might be more involved and so it's often not as simple. But perhaps having a method that sets everything up and returns result of `alpaka::mem::buf::alloc<myStrct, Idx>(devAcc, sizeof(myStruct));` is feasible, so that you just initialize with the result of this function.
- Instead of having a value as a member, have a (smart) pointer instead and initialize inside the constructor body when you know proper arguments
- (This is more heavy investment) In case you really like buffers to have such default construction, could write a wrapper around it which internally uses a pointer or somehow constructs an empty buffer and later resets it.

**Comment by waredjeb** [comment]
@sbastrakov thanks for the suggestions, I'll try these ways and I'll let you know!

**Comment by BenjaminW3** [comment]
Initializing the buffer in the [constructors member initializer list](https://en.cppreference.com/w/cpp/language/initializer_list) would be the correct way.
If this is really not possible, you could also use an `optional<TBufD>` if you already depend on boost (`boost::optional`) or if you use c++17 (`std::optional`).
I will close this for now. Please reopen the issue if it did not work!
