### ISSUE TITLE
Add support for CUDA 10.2

### ISSUE THREAD

**Issue by BenjaminW3** [alpaka-group/alpaka#885]
We should add CUDA 10.2 to CI.

Notable things from the Release Notes:
* `"nvcc now supports a new flag -Werror=all-warnings to turn all generated warnings into errors instead."` I will try this out.
* `"Add option -forward-unknown-to-host-compiler to nvcc that allows forwarding of options not recognized by nvcc to the host compiler."` May this be useful for us?
* `"CUDA 10.2 (Toolkit and NVIDIA driver) is the last release to support macOS for developing and running CUDA applications. Support for macOS will not be available starting with the next release of CUDA."` We never officially supported this but now it is declared dead.
* `"Support for Kepler sm_30 architecture based products will be dropped starting with the next release of CUDA."` I did not find any code in alpaka that is dependent on this version. When `sm_35` is removed we can remove some workarounds.

**Comment by psychocoderHPC** [comment]
> We should add CUDA 10.2 to CI.
> 
> Notable things from the Release Notes:
> 
> * `"nvcc now supports a new flag -Werror=all-warnings to turn all generated warnings into errors instead."` I will try this out.
> * `"Add option -forward-unknown-to-host-compiler to nvcc that allows forwarding of options not recognized by nvcc to the host compiler."` May this be useful for us?

I think it is a nice feature but since we still need to handle the old cuda versions I would keep explicit option handling.

> * `"CUDA 10.2 (Toolkit and NVIDIA driver) is the last release to support macOS for developing and running CUDA applications. Support for macOS will not be available starting with the next release of CUDA."` We never officially supported this but now it is declared dead.

+1

> * `"Support for Kepler sm_30 architecture based products will be dropped starting with the next release of CUDA."` I did not find any code in alpaka that is dependent on this version. When `sm_35` is removed we can remove some workarounds.

As I remember we only set for testing explicit sm_35 or so. Never the less we need to update our cmake because we activate sm_30 if CUDA 9+ is used https://github.com/ComputationalRadiationPhysics/alpaka/blob/066a2e9c30edd09d2831ef9ef8f69cce8fbcb120/alpakaConfig.cmake#L432-L436
If we fix this now and add the lines that for CUDA 11+ the default is sm_60 than we have a high change that the next alpaka release will run on CUDA 11 without other changes.
